
openapi: 3.1.0
info:
  title: UIP Admin API
  version: 1.0.0
paths:
  /admin/engines/{engine}:
    post:
      summary: Propose configuration change
      parameters:
        - name: engine
          in: path
          required: true
          schema:
            type: string
      responses:
        '202':
          description: Pending approval
